import Head from "next/head";
import { Table } from "~/components/Table";
import { Timeline } from "~/components/Timeline";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col justify-center gap-12 px-4 py-16 ">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Easy <span className="text-[hsl(280,100%,70%)]">Karaoke</span> Maker
        </h1>
        <Table />
      </div>
    </>
  );
}
